kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DBAdmin
  namespace: backup # TODO: Re-run this file with other necessary ns
rules:
# TODO:
# target all resources with full access
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DBAdminBinding
  namespace: backup # TODO: Re-run this file with other necessary ns, match with role above
subjects:
- kind: User
  name: Jessica
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: DBAdmin
  apiGroup: rbac.authorization.k8s.io
